FROM 10.50.1.63:5443/hub/tiangolo/uwsgi-nginx-flask:python3.8

RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple flask flask-json pyyaml

#ADD . / app/
# Last time is using copy
#COPY . /app

COPY ./app /app
